export const FEATURE_STATUSES = {
  transferred: "Transferred to current new UI",
  backendReady: "Backend copied; UI pending",
  proxyReady: "Legacy proxy route available",
  leftOut: "Left out for now",
};

export const BACKEND_FEATURES = [
  {
    id: "audio-upload",
    area: "Audio",
    status: "transferred",
    oldSource: "src/components/screens/UploadAudioScreen.js",
    backendRoute: "/api/studio/upload-audio",
    newUiSurface: "Audio Upload",
    notes: "Uploads audio to Supabase storage and updates projects.audio_url for the selected project.",
  },
  {
    id: "audio-analysis",
    area: "Audio",
    status: "transferred",
    oldSource: "src/app/api/analyze/route.js",
    backendRoute: "/api/analyze",
    newUiSurface: "Player and Analysis",
    notes: "Runs Gemini transcript analysis, stores project_state.analysis, rehydrates retained analysis on project reopen, and renders BPM, duration, lyric count, full lyrics, word timing, and summary.",
  },
  {
    id: "project-dashboard-backend",
    area: "Account",
    status: "transferred",
    oldSource: "src/app/dashboard/page.js",
    backendRoute: "/api/dashboard/projects, /api/dashboard/projects/[projectId]",
    newUiSurface: "Dashboard",
    notes: "Uses Supabase auth or bearer token context to list and create projects, hydrates saved audio/analysis by project id, and deletes projects plus Supabase assets through /api/dashboard/projects. Demo rows render when auth is not connected.",
  },
  {
    id: "script-plan",
    area: "Story",
    status: "transferred",
    oldSource: "src/app/api/generate-script/route.js",
    backendRoute: "/api/generate-script",
    newUiSurface: "Script Upload and Script Analysis",
    notes: "Generate Script From Lyrics reuses the backend script generator and persists script, characters, and locations into project_state. Draft shot ideas stay under script.draft_shot_ideas until the user creates a shot plan.",
  },
  {
    id: "script-scene-approval",
    area: "Story",
    status: "transferred",
    oldSource: "project_state.script.scenes",
    backendRoute: "/api/studio/save-script-analysis",
    newUiSurface: "Script Analysis",
    notes: "Editable high-level scenes can be inserted, removed, reordered, and saved back into project_state.script.scenes before proceeding.",
  },
  {
    id: "script-file-extraction",
    area: "Story",
    status: "transferred",
    oldSource: "src/app/api/extract-script-file/route.js",
    backendRoute: "/api/extract-script-file",
    newUiSurface: "Script Upload",
    notes: "The script upload surface stores PDF/TXT/MD files in project assets and persists extracted raw text plus metadata into project_state.script.",
  },
  {
    id: "script-entity-previews",
    area: "Story",
    status: "transferred",
    oldSource: "project_state.characters, project_state.locations, project_state.script.file_detected_entities",
    backendRoute: "/api/studio/extract-script, /api/studio/generate-script",
    newUiSurface: "Brain Hub, Characters, Locations",
    notes: "After script analysis, the Brain Hub marks script done and unlocks character/location canvases seeded with one draggable empty template per retained project_state entity.",
  },
  {
    id: "brain-dump-refinement",
    area: "Story",
    status: "backendReady",
    oldSource: "src/app/api/process-wardrobe-brain-dump/route.js",
    backendRoute: "/api/process-wardrobe-brain-dump",
    newUiSurface: "Not surfaced yet",
    notes: "Needs character/location/style inputs that are not present in the current new UI.",
  },
  {
    id: "knowledge-base",
    area: "Project Memory",
    status: "transferred",
    oldSource: "src/app/api/build-knowledge-base/route.js",
    backendRoute: "/api/build-knowledge-base",
    newUiSurface: "Character/Location/Wardrobe saves",
    notes: "The local studio route loads latest project_state, reuses the frozen KB builder, and schedules rebuilds after supported entity/wardrobe saves. The former Shots gate rebuild trigger is not mounted in the current Studio canvas.",
  },
  {
    id: "cast-generation",
    area: "Cast",
    status: "backendReady",
    oldSource: "src/app/api/generate-character-anchor/route.js",
    backendRoute: "/api/generate-character-anchor",
    newUiSurface: "Characters canvas template only",
    notes: "Character templates are seeded, but anchor/pose generation and library persistence still need dedicated controls.",
  },
  {
    id: "location-generation",
    area: "Locations",
    status: "backendReady",
    oldSource: "src/app/api/generate-location-image/route.js",
    backendRoute: "/api/generate-location-image",
    newUiSurface: "Locations canvas template only",
    notes: "Location templates are seeded, but generation, sheet splitting, and library persistence still need dedicated controls.",
  },
  {
    id: "wardrobe-outfits",
    area: "Wardrobe",
    status: "transferred",
    oldSource: "project_state.wardrobe",
    backendRoute: "/api/studio/save-wardrobe",
    newUiSurface: "Character template wardrobe section",
    notes: "The wardrobe section inside each character template exposes a horizontally scrollable outfit strip, uploads multiple outfit references, persists outfit text, and writes character-level outfit rows while continuing to read legacy location/outfit matrix rows.",
  },
  {
    id: "wardrobe-generation",
    area: "Wardrobe",
    status: "backendReady",
    oldSource: "src/app/api/generate-wardrobe-outfit/route.js",
    backendRoute: "/api/generate-wardrobe-outfit",
    newUiSurface: "Not surfaced yet",
    notes: "Outfit text and image generation require cast/location/wardrobe screens.",
  },
  {
    id: "shot-planning",
    area: "Shots",
    status: "transferred",
    oldSource: "src/app/api/generate-shot-list/route.js",
    backendRoute: "/api/generate-shot-list, /api/studio/save-shot-plan, /api/studio/save-shot-timing",
    newUiSurface: "Rocket launch checkpoint + Studio edit action",
    notes: "Navigation to Shots is paused when no saved shot plan exists. The checkpoint supports upload/paste/generate and saves shot_list plus shot_list_meta; Studio exposes Edit Shot Plan and debounced exact duration saves from scene timelines.",
  },
  {
    id: "shot-media",
    area: "Media Generation",
    status: "backendReady",
    oldSource: "src/app/api/generate-shot-image/route.js",
    backendRoute: "/api/generate-shot-image, /api/generate-shot-video, /api/rewrite-shot-prompt",
    newUiSurface: "Not surfaced yet",
    notes: "Shot image/video generation and prompt rewrite await shot and clip pages.",
  },
  {
    id: "editor-render",
    area: "Assembly",
    status: "backendReady",
    oldSource: "src/app/api/shotstack/render/route.js",
    backendRoute: "/api/shotstack/render",
    newUiSurface: "Not surfaced yet",
    notes: "Shotstack rendering requires the future editor/assembly page and Python sidecar.",
  },
  {
    id: "auth-profile-billing",
    area: "Account",
  status: "leftOut",
    oldSource: "src/app/page.js, src/app/profile/page.js, src/app/billing/page.js",
    backendRoute: "Supabase auth/client flows and Stripe checkout",
    newUiSurface: "Not present",
    notes: "Login, signup, profile, credits, and billing screens are outside the current dashboard/audio flow.",
  },
  {
    id: "python-sidecar-runtime",
    area: "Infrastructure",
  status: "backendReady",
    oldSource: "python-service/",
    backendRoute: "PYTHON_SERVICE_URL",
    newUiSurface: "Not present",
  notes: "Python sidecar source is copied into new-ui/python-service, but the Next app still expects it to be launched separately for render/editor routes.",
  },
];

export function featuresWithStatus(status) {
  return BACKEND_FEATURES.filter((feature) => feature.status === status);
}
